# Site settings
title: artyfarty
email: mail@artyfarty.io
description:  "Arty's homepage"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://artyfarty.io" # the base hostname & protocol for your site
twitter_username: molecularperson
github_username:  artyfarty

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md